#cloud-config
#
# Set Hostname
hostname: coreos

# Set SSH Key:
ssh_authorized_keys:
  - <!!!INSERT_SSH_KEY_HERE!!!> 

coreos:
  etcd:
    discovery: <!!!INSERT_DISCOVERY_TOKEN_HERE!!!>

  units: 
  - name: static.network
    content: |   
      [Match]
        Name=eth1

        [Network]
        Address=192.168.56.110/24 
        Gateway=0.0.0.0
        DNS=8.8.8.8
        DNS=8.8.4.4

# Disable Password Authentication
write_files:
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
      # Use most defaults for sshd configuration.
      UsePrivilegeSeparation sandbox
      Subsystem sftp internal-sftp

      PermitRootLogin no
      AllowUsers core
      PasswordAuthentication no
      ChallengeResponseAuthentication no
