#cloud-config
#
# Set Hostname
hostname: coreos

# Set SSH Key:
ssh_authorized_keys:
  - <!!!INSERT_PUB_SSH_KEY_HERE!!!>

coreos:
  etcd:
    discovery: <!!!INSERT_DISCOVERY_TOKEN_HERE!!!>

# Disable Password Authentication
write_files:
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
      # Use most defaults for sshd configuration.
      UsePrivilegeSeparation sandbox
      Subsystem sftp internal-sftp

      PermitRootLogin no
      AllowUsers core
      PasswordAuthentication no
      ChallengeResponseAuthentication no
